name: CI
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  pull:
    runs-on: TS2-Testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: external-txt
